### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by Katreenlooper** [Fzaero/Deep-Effect-Trajectory-Prediction-in-Robot-Manipulation#2]
Hey,
I have question related to datasets.
I downloaded the datasets from the website (https://zenodo.org/record/2556671#.XrmPkRaxW0k) but could you tell me how should i organize them?
I mean inside (Lever_up_Trajectories) there are many directories (shapes , gen3 .. , shape0 , edge etc). So how can i run the module successfully on this datasets? I tried my best but i faced some problems.
One more thing, where can i see the paper for this work?
I appreciate your help.
Thanks

**Comment by Fzaero** [comment]
Hello,
Naming of directories correspond to dataset hierarchy:
3gen,4gen,etc : These corresponds to shapes with 3-sided(Triangle), 4-sided shapes.
shape0, shape1 : For each corresponding shape type(eg. triangle ) we have 20 generated different shapes.
edge0,edge1: This correspond to edge that object is levered-up. Depending on how many side object have, amount of edge changes. Eg 3-sided objects have three edge folder(edge0, edge1, edge2) 
For each edge we have 2 lever-up experiment.

For starting you can check setup_data.py(https://github.com/Fzaero/Deep-Effect-Trajectory-Prediction-in-Robot-Manipulation/blob/master/src/Setup_Data.py). There may be some errors with pathing but what you can do is that:
* Copy Setup_Data.py to upper directory.
* Put shapes folder to this directory.
* Create two empty folder named trajectories and images.
* Run Setup_Data.py

This should generate the dataset. You can further ask me if there is something I missed.

Best,
Ahmet

**Comment by Fzaero** [comment]
Paper can be reached at : https://www.sciencedirect.com/science/article/abs/pii/S0921889019300740

There is also a preprint version: https://www.cmpe.boun.edu.tr/~emre/papers/Seker-2019-ROBOT.pdf

**Comment by Katreenlooper** [comment]
Hey Ahmet,
Thank you very much for your response.
It works (the datasets are successfully generated), but i have some configuration problems when i run (Training_Models).
I know the scripts are written in python(2.7) and i tried tensorflow (1.4), but i am still facing some problems (with tensorflow 2.0 and keras 2.1.5 the same issue ).
The problem in Models.py is that (CuDNNLSTM) is not recognized (I tried 'from tensorflow.python.keras.layers import ..' instead of 'from keras.layers import ..').
Could you please tell me, what are the exact requirements or prerequisites (keras, tensorflow etc.) ?
Thank you again.
Best Regards

**Comment by Fzaero** [comment]
CuDNNLSTM is available only in tensorflow-gpu maybe that may be the reason. You can also change CuDNNLSTM's to LSTM if tensorflow-gpu is not available.

Scripts was written in the tensorflow 1.14 I think but I'm not sure. But it shouldn't cause any trouble.
